### ISSUE TITLE
Not importing correctly

### ISSUE THREAD

**Issue by crptz** [Kaesebrot84/hips-lib#1]
Hey !

As I'm trying your crate it seems like something is off when importing.

In your README file you say to use:
```
iris-lib = { version = "0.1.0", features = ["image"]}
```

and 

```
use hips_lib::hips::{find_secret_img, hide_secret_img};
```

But when importing I'm getting error that `find_secret_img` and `hide_secret_img` don't exist.

I can see the functions inside `hips.rs` file but something is off

These are my errors
![image](https://user-images.githubusercontent.com/77761282/220338289-9285a640-d012-4847-a7e0-1af0b7cf98e7.png)

My `Cargo.toml` file
![image](https://user-images.githubusercontent.com/77761282/220338493-cba5355a-cc33-4fa4-9932-44a8928c0542.png)

I'm not sure what am I missing here.

Also, love your work !

**Comment by Kaesebrot84** [comment]
Hi there,

this is my fault. I added the wrong package in the README file.

What you have to change is the name in your Cargo.toml

Use `hips-lib = ...` instead of `iris-lib`.

My fault, will fix it asap!

**Comment by crptz** [comment]
Oh man, I imagined this was the problem but I forgot to remove image crate from my toml file and this was making a conflict and I thought that hips-lib is wrong too.

Anyway now it works perfect, thank you !

**Comment by Kaesebrot84** [comment]
> Oh man, I imagined this was the problem but I forgot to remove image crate from my toml file and this was making a conflict and I thought that hips-lib is wrong too.
> 
> 
> 
> Anyway now it works perfect, thank you !

Glad you like it and thanks for your feedback 👍
